### ISSUE TITLE
Examples for dummies?

### ISSUE THREAD

**Issue by moltubakk** [myselfhimself/gmic-py#38]
Thanks a lot for your work! I see that you have started adding examples. Are there any chance that you could add a few basic examples for how to manipulate an image from a file and output it to file?

**Comment by myselfhimself** [comment]
yes good idea!
Let me come back to you. Have you written after viewing the LGM2020 presentation?

**Comment by moltubakk** [comment]
No, I ended up at your project after a bit of googling... I've managed a little bit on my own, but need some basics that I haven't been able to find. 

...now I just found the LGM2020 page... do you know if the presentations will be available afterwards?

**Comment by myselfhimself** [comment]
My [presentation is here and shows basics of gmic-py](https://drive.google.com/file/d/1YdFqIiYmZBPElqVwWGeseO-5mpc-Jtjp/view?usp=sharing). There are going to be 3-4 more presentations tomorrow according to the [program of the LGM2020](https://libregraphicsmeeting.org/2020/en/program.html).

In very short until I commit examples for simple G'MIC usage, for file input and output you do as follows:
```
import gmic
gmic.run("myfiletoopen.somecommongraphicsextension your gmic operations output myfiletosaveto")
#example 
gmic.run("a.png blur 3 output b.png")
#also you can use the display command on linux to show quickly your result
gmic.run("a.png display")
#note also you can use sample images stored in gmic
gmic.run("sp earth display blur3 output myearth.png")

#running gmic.run many times is slow because each gmic.run stars a new gmic interpreter which warms up a bit
#the more efficient way is to use a single gmic runner instance
g = gmic.Gmic()
g.run("some operation")
g.run("some other operation")
g.run("etc")
```
gmic supports many image file formats, no just png, have a try simply with what you have around
That was for an intro.. I will document this into example files soon :)

**Comment by moltubakk** [comment]
Thanx a lot! Now it works! Now I've got something to play with. Among my problems were the fact that I was not able to make jpg files work.  Now I'm quite sure WSL (Ubuntu) at Win10 was the reason. I've tested in a container, and it works like a charm! Great! Thanks again!

**Comment by myselfhimself** [comment]
Hello moltubakk,
nice!!!
I know well WSL because I worked at Microsoft last year.....
We want to compile G'MIC-py to windows soon using the MSYS2 stack (or have
some compile for MSVC++ if they prefer..). It is just a second priority
after the ongoing numpy support writing. Feel free to help if you know
about compiling tricks on Windows. Note that also that I will automatize
the compilation step into Github Actions to have new builds per commit or
tag once the steps are ok.
Note also that if some filters do not seem to exist despite their being
listed in official documentations of gmic.eu or G'mic community's third
party filters
<https://github.com/dtschump/gmic-community/tree/master/include> (available
for gmic update 1 hour after PR merge), you can run "gmic update" inside an
gmic run, and maybe restart an interpreter and you shall notice new filters
working after some internet retrieval. The gmic version you have (2.8.4
most probably, visible in gmic.__package__ or gmic.__build__ or
gmic.__version__ I don't remember) relies possible on linux-installed curl
to retrieve updates.
Upcoming gmic-py versions will embed libcurl thanks to an upstream fix in
auditwheel.. Anyway much technique.
Enjoy!!
Jonathan-David

čt 28. 5. 2020 v 23:54 odesílatel moltubakk <notifications@github.com>
napsal:

**Comment by myselfhimself** [comment]
Here is the most advanced existing gmic-py example on the web so far to my
knowledge.
<https://github.com/myselfhimself/BerlinWallBreaker/blob/master/assets/generation/make_map.py>

pá 29. 5. 2020 v 9:34 odesílatel Jonathan-David SCHRODER <
jonathan.schroder@gmail.com> napsal:

**Comment by myselfhimself** [comment]
@moltubakk do you need more help or can I close this issue?

**Comment by moltubakk** [comment]
Please go ahead and close it! This was excellent help. Unfortunately, I've been too busy to be able to complete my hobby project. But now I have the tools needed. Good luck with your work!
